### ISSUE TITLE
docs: ISO misinfo

### ISSUE THREAD

**Issue by xynydev** [tulilirockz/Atomic-Studio#16]
The iso made by the iso action is not actually an offline ISO, unlike what the README states.

Offline ISO generation instructions are here:
https://blue-build.org/learn/universal-blue/#fresh-install-from-an-iso

Those ISOs will most likely be too large for GH releases, so another hosting provided would be needed.

**Comment by tulilirockz** [comment]
yeah its not yet an offline ISO
its just that this is not still a public project, this will actually be useful for other people whenever this stuff gets done

**Comment by tulilirockz** [comment]
ill change that in the readme anyways! thank you for the heads up
