### ISSUE TITLE
feat: studio wine command

### ISSUE THREAD

**Issue by tulilirockz** [tulilirockz/Atomic-Studio#28]
- Will need to install Pipewire-wineasio and some other asio things for this! https://www.youtube.com/watch?v=zmmdyX381Go

- wine run just runs anything through wineTKG (including installers
- wine export: exports wine apps to the host
- wine manager runs some wine manager that uses the studio-wine prefix
- wine install: parses bottles yml files and installs stuff using installer scripts

**Comment by fiftydinar** [comment]
Interested in this, as I prefer to use FL Studio as a DAW.

**Comment by tulilirockz** [comment]
this should work with fl studio or reaper as it uses wineTKG! i still need to implement this in a graphical (or at least TUI) way tho! most likely through a wine manager interface or something like that.

**Comment by fiftydinar** [comment]
Regarding the video you linked above for some tweaks, you can take an inspiration from CachyOS Settings, as they have some of those related to audio:
https://github.com/CachyOS/CachyOS-Settings

PS: Using FL Studio ASIO was a pain, couldn't play anything properly because of high latency. I heard about WineASIO, but I didn't know how to set that up back then.

**Comment by tulilirockz** [comment]
Added the CachyOS audio-related configuration files with 31ac103

**Comment by fiftydinar** [comment]
> Added the CachyOS audio-related configuration files with [31ac103](https://github.com/atomic-studio-org/Atomic-Studio/commit/31ac1037788cb2a65b058993c97d674fa781f60e)

I am not sure if those @realtime & @audio user groups need to be created before inserting those there.

Nvidia config is tailored for their Arch Nvidia driver, things for Fedora might be different, so I wouldn't risk the bisquit.

For Esync to work, you would also need systemd configuration drop-in:
https://github.com/fiftydinar/gidro-os/blob/main/config/systemd/system.conf.d/nolimit-gidro.conf
https://github.com/fiftydinar/gidro-os/blob/main/config/systemd/user.conf.d/nolimit-gidro.conf
It would be great to also increase softfile nofile limit to 4096 in 99-esync.conf.

About HPET permissions & interrupts, I don't think that's complete, as they use that script in temp folder, which implies they are passing that for something else.

For now, I would just merge this useful binary for PCI latency & it's systemd service:
https://github.com/CachyOS/CachyOS-Settings/blob/master/usr/bin/pci-latency
https://github.com/CachyOS/CachyOS-Settings/blob/master/etc/systemd/system/pci-latency.service

For the rest, I will see what to do & what needs to be implemented fully.
Nice & steady is the way.

I can make a PR reverting those modifications & doing what I mentioned here.
Is that cool?

**Comment by tulilirockz** [comment]
Yeah! No prob!

**Comment by fiftydinar** [comment]
https://github.com/atomic-studio-org/Atomic-Studio/pull/64

**Comment by tulilirockz** [comment]
I tried the approach of having Wine-TKG installed on the host, but sadly that won't be possible because TKG made a patch to wine-tkg-git forcing fedora builds to use the experimental wow64 driver for wine, which cannot run anything! Ive tried to install anything, like FL-Studio, Reaper, or even Notepad++ and it didnt work :(. Ill be working on a workaround tomorrow by using a custom archlinux container with wine-tkg installed. The studio cli will use that instead of the system provided wine (which will be removed). Id love to have a GUI or TUI for wine, im pretty sure ill have to implement  that too

**Comment by fiftydinar** [comment]
> I tried the approach of having Wine-TKG installed on the host, but sadly that won't be possible because TKG made a patch to wine-tkg-git forcing fedora builds to use the experimental wow64 driver for wine, which cannot run anything! Ive tried to install anything, like FL-Studio, Reaper, or even Notepad++ and it didnt work :(. Ill be working on a workaround tomorrow by using a custom archlinux container with wine-tkg installed. The studio cli will use that instead of the system provided wine (which will be removed). Id love to have a GUI or TUI for wine, im pretty sure ill have to implement that too

Wine on host is dependency hell anyway, so good ridance I guess.
Bottles may sound great as GUI when it's using Adwaita theme, but it's much more complicated to install & manage applications there.
If there could be some wine GUI which would automatically handle prefix-per-app approach like Steam does, that would be great

**Comment by tulilirockz** [comment]
This issue is gonna get moved over to the relevant [studio-cli](https://github.com/atomic-studio-org/studio-cli) repository, check it out instead of this one!
