### ISSUE TITLE
limitation: Secure Boot is not supported using custom kernel (in this case, fsync)

### ISSUE THREAD

**Issue by fiftydinar** [tulilirockz/Atomic-Studio#55]
You need to use kernel signer action from EyeCantCU to achieve that.

For now, please note that limitation in README.

Relevant issue:
https://github.com/blue-build/modules/issues/148

**Comment by tulilirockz** [comment]
yooo thats why it didnt work! Ill revert my revert with the proper github action now! thank you very much!

**Comment by tulilirockz** [comment]
Heyo! Now that I've changed the main build action to a custom one for metadata, we can integrate the kernel signer!

**Comment by tulilirockz** [comment]
This issue should be fixed now! I just need to test this out on a VM to make sure this works first

**Comment by fiftydinar** [comment]
This issue is blocked by upstream due to the way `rpm-ostree cliwrap install-to-root /` is handled in `bluebuild-cli` for installing custom kernels.

Related issue:
https://github.com/blue-build/cli/issues/119

**Comment by tulilirockz** [comment]
This issue should be fixed now with the newest bluebuild CLI! ill be testing this out and checking if this works

**Comment by tulilirockz** [comment]
This issue should be fixed now with the newest bluebuild CLI! ill be testing this out and checking if this works
