### ISSUE TITLE
chore: move over to Other Templating Engine (pkl ideally)

### ISSUE THREAD

**Issue by tulilirockz** [tulilirockz/Atomic-Studio#68]
Containerfiles are better for this project because it would be easier to contribute to, and having less abstrations makes it so knowing what the hell is in the image a lot easier, and we wouldnt need the `jsonnet -> yaml/bluebuild -> containerfile` dynamic.

**Comment by fiftydinar** [comment]
:(

**Comment by fiftydinar** [comment]
I'm interested to know how would Containerfile look at the end, to see what is the difference in implementation & structure.

I thought about doing this for Bluefin in a opposite way, which is possible imo, but Bluefin is not something I use daily, so I scratched that.

**Comment by xynydev** [comment]
I assume the structure would look more like ubluemain or bluefin. IMO this is `refactor:` though. 

Also keep in mind that you can keep using BlueBuild modules for stuff like Flatpaks if you decide to refactor, I can walk you through that if that's desireable. 

We're of course also interested in specific frustrations you've had with BB (even if you believe that they can't be fixed) and what you hope to gain from a refactor.

I find this project pretty interesting as a creative myself, so I have taken a good look at the source code and config, and do have some thoughts on how I'd refactor it within the system.

**Comment by tulilirockz** [comment]
Honestly using bluebuild has been amazing! The only thing is that there are multiple layers of abstraction and that makes it so that refactoring stuff is a tiny bit confusing Im thinking about just moving everything over to apple pkl (including the modules) so that it might have a bit less layers that we need to work with (jsonnet + yaml -> containerfile vs pkl -> yml -> containerfile)

**Comment by tulilirockz** [comment]
Honestly using bluebuild has been amanzing! The only thing is that there are multiple layers of abstraction and that makes it so that refactoring stuff is a tiny bit confusing Im thinking about just moving everything over to apple pkl (including the modules) so that it might have a bit less layers that we need to work with (jsonnet + yaml -> containerfile vs pkl -> yml -> containerfile)

**Comment by xynydev** [comment]
If you get pkl working, let me know. I've been trying a bunch of stuff [here](https://github.com/blue-build/cli/issues/140#issuecomment-2027993157), but haven't tried pkl yet due to finding the docs kind of hard to read, not finding the info I'm looking for, etc.

**Comment by tulilirockz** [comment]
Pkl is pretty nice! Implemented stuff with [b67f8c6](https://github.com/atomic-studio-org/Atomic-Studio/commit/b67f8c6ea4afea5c833ec8540492a157cd3e690d). :+1:

**Comment by xynydev** [comment]
Isn't this "not planned", and not "completed"?

**Comment by tulilirockz** [comment]
Well, true! I guess this issue was just for moving to something other that raw yaml files
