### ISSUE TITLE
Miniaturo GTK RAW pictures thumbnailer

### ISSUE THREAD

**Issue by fiftydinar** [tulilirockz/Atomic-Studio#76]
### Describe the package

Since this package does not fit into scope of main Universal Blue images, as it's only available in COPR, this image should utilize this package, to help photographers in better RAW images integration into file manager.

Only works in Gnome image.

COPR: https://copr.fedorainfracloud.org/coprs/decathorpe/miniaturo/
Project: https://github.com/dbrgn/miniaturo

Just `rpm-ostree install miniaturo` after adding the COPR & that's it.

COPR package already utilizes the workaround for shipping .thumbnailer & xml file for auto-thumbnailing adopted from depreciated raw-thumbnailer, which upstream Miniaturo project doesn't currently support as a functionality.

I didn't want to make a PR, as you're in a process of migration to Containerfile, so I didn't want to disrupt that.

### Image

Gnome

**Comment by tulilirockz** [comment]
ill be adding it! Not in the process of migrating over to Containerfile anymore tho! Ill be seeing if pkl is a nice idea, worst case ill just keep on using jsonnet n yaml

**Comment by tulilirockz** [comment]
Done with 428d89a :+1:
