### ISSUE TITLE
Maybe a -minimal version (without all the thousands of preinstalled packages)

### ISSUE THREAD

**Issue by tulilirockz** [tulilirockz/Atomic-Studio#79]
Maybe it would be cool to have a very small image with just the improvements from Atomic Studio without all the 100 bilion apps that we add by default, that will allow people with less storage to use this image (E.G.: I need to make a VM with literally 60 GBs or space to test this image.)

**Comment by xynydev** [comment]
Tons of these billions of apps could already be made optional with the new Yafti soon IMO. Or even just through `studio add`. Pre-installed software is useful for offline environments and discovering new things, though, but I think a `-minimal` image is the bare minimum.

**Comment by tulilirockz** [comment]
I guess the best way to go forward is to make the default images the minimal ones, and make a new tag named `-fx` (like swayfx), that would have a bunch of stuff included by default. It would be a pattern a lot like bluefin and bluefin-dx!

**Comment by tulilirockz** [comment]
Done with 4b6e39919fab8e8ac1cbc0ce1763c6be471613f6 :+1:
